### PR TITLE
Release `v2.1.0`

### PR DESCRIPTION
**Pull request by robbot006**
This is a draft of changelog for the `v2.1.0` release.
Here you can find all related translations changes: [v2.0.17...master](https://github.com/flarum-lang/hungarian/compare/v2.0.17...master).

> ### ⚠️ Do not merge this pull request manually ⚠️
> 
> You should [approve](https://github.com/rob006-software/flarum-translations/wiki/How-to-approve-release-pull-request) this pull request instead. After approving, I will automatically update it (release date needs to be adjusted), merge, and tag a new release.

<details>
<summary>Show release notes preview</summary>

## v2.1.0

**General changes**:

* Updated Flarum core translations.

**Added support for new extensions**:

* [`clarkwinkelmann/flarum-ext-discussion-bookmarks`](https://github.com/clarkwinkelmann/flarum-ext-discussion-bookmarks)
* [`clarkwinkelmann/flarum-ext-ipsum-autocomplete`](https://github.com/clarkwinkelmann/flarum-ext-ipsum-autocomplete)
* [`clarkwinkelmann/flarum-ext-see-past-first-post`](https://github.com/clarkwinkelmann/flarum-ext-see-past-first-post)
* [`clarkwinkelmann/flarum-ext-shadow-ban`](https://github.com/clarkwinkelmann/flarum-ext-shadow-ban)
* [`clarkwinkelmann/flarum-ext-who-read`](https://github.com/clarkwinkelmann/flarum-ext-who-read)
* [`datitisev/flarum-discussion-agree-message`](https://github.com/datitisev/flarum-discussion-agree-message)
* [`datlechin/flarum-bbcode-hide-content`](https://github.com/datlechin/flarum-bbcode-hide-content)
* [`datlechin/flarum-copy-links`](https://github.com/datlechin/flarum-copy-links)
* [`datlechin/flarum-discussion-overview`](https://github.com/datlechin/flarum-discussion-overview)
* [`datlechin/flarum-landing-page`](https://github.com/datlechin/flarum-landing-page)
* [`datlechin/flarum-link-preview`](https://github.com/datlechin/flarum-link-preview)
* [`datlechin/flarum-more-discussions`](https://github.com/datlechin/flarum-more-discussions)
* [`datlechin/flarum-offline-indicator`](https://github.com/datlechin/flarum-offline-indicator)
* [`datlechin/flarum-scroll-buttons`](https://github.com/datlechin/flarum-scroll-buttons)
* [`datlechin/flarum-tag-passwords`](https://github.com/datlechin/flarum-tag-passwords)
* [`datlechin/flarum-title-length`](https://github.com/datlechin/flarum-title-length)
* [`davwheat/flarum-ext-ads`](https://github.com/davwheat/flarum-ext-ads)
* [`dem13n/discussion-cards`](https://github.com/Dem13n/discussion-cards)
* [`extiverse/mercury`](https://github.com/extiverse/mercury)
* [`flamarkt/backoffice`](https://github.com/flamarkt/backoffice)
* [`flamarkt/matomo`](https://github.com/flamarkt/matomo)
* [`flamarkt/taxonomies`](https://github.com/flamarkt/taxonomies)
* [`fof/discussion-thumbnail`](https://github.com/FriendsOfFlarum/discussion-thumbnail)
* [`fof/mason`](https://github.com/FriendsOfFlarum/mason)
* [`fof/sentry`](https://github.com/FriendsOfFlarum/sentry)
* [`fof/username-request`](https://github.com/FriendsOfFlarum/username-request)
* [`fof/webhooks`](https://github.com/FriendsOfFlarum/webhooks)
* [`ganuonglachanh/sonic`](https://github.com/ganuonglachanh/flarum-sonic)
* [`glowingblue/password-strength`](https://github.com/glowingblue/flarum-ext-password-strength)
* [`glowingblue/redis-setup`](https://github.com/glowingblue/flarum-ext-redis-setup)
* [`ianm/gravatar`](https://github.com/imorland/gravatar)
* [`ianm/oauth-amazon`](https://github.com/imorland/flarum-ext-oauth-amazon)
* [`jslirola/flarum-ext-login2seeplus`](https://github.com/jslirola/flarum-ext-login2seeplus)
* [`justoverclock/auto-post-count-badge`](https://github.com/justoverclockl/auto-post-count-badge)
* [`justoverclock/best-answer-badge`](https://github.com/justoverclockl/best-answer-badge)
* [`justoverclock/broken-links-checker`](https://github.com/justoverclockl/broken-links-checker)
* [`justoverclock/country-flags`](https://github.com/justoverclockl/country-flags)
* [`justoverclock/custom-header`](https://github.com/justoverclockl/custom-header)
* [`justoverclock/edit-posts`](https://github.com/justoverclockl/edit-posts)
* [`justoverclock/events-countdown`](https://github.com/justoverclockl/events-countdown)
* [`justoverclock/flarum-ext-feedback`](https://github.com/justoverclockl/flarum-ext-feedback)
* [`justoverclock/flachat`](https://github.com/justoverclockl/flachat)
* [`matteocontrini/flarum-imgur-upload`](https://github.com/matteocontrini/flarum-imgur-upload)
* [`migratetoflarum/fake-data`](https://github.com/migratetoflarum/fake-data)
* [`nearata/flarum-ext-embed-video`](https://github.com/Nearata/flarum-ext-embed-video)
* [`nearata/flarum-ext-tags-color-generator`](https://github.com/Nearata/flarum-ext-tags-color-generator)
* [`sycho/flarum-advanced-extension-categories`](https://github.com/SychO9/flarum-advanced-extension-categories)
* [`sycho/flarum-move-posts`](https://github.com/SychO9/flarum-move-posts)
* [`the-turk/flarum-diff`](https://github.com/the-turk/flarum-diff)
* [`the-turk/flarum-stickiest`](https://github.com/the-turk/flarum-stickiest)
* [`therealsujitk/flarum-ext-gifs`](https://github.com/therealsujitk/flarum-ext-gifs)
* [`tituspijean/flarum-ext-auth-ldap`](https://github.com/tituspijean/flarum-ext-auth-ldap)
* [`xelson/flarum-ext-chat`](https://github.com/Xelson/flarum-ext-chat)

**Updated translations for extensions**:

* [`blomstra/payments`](https://extiverse.com/extension/blomstra/payments)
* [`clarkwinkelmann/flarum-ext-scout`](https://github.com/clarkwinkelmann/flarum-ext-scout)
* [`justoverclock/flarum-ext-hashtag`](https://github.com/justoverclockl/flarum-ext-hashtag)

All changes: [v2.0.17...v2.1.0](https://github.com/flarum-lang/hungarian/compare/v2.0.17...v2.1.0).

</details>

### CODE REVIEW

**Comment by rob006** [comment]
@Rebootcodesoft @meskobalazs Just as a note, this is an automated PR generated by bot. The idea is to simplify release process for language pack maintainers - all you need is to approve this pull request and bot will handle the rest. You can read more about the process at forum: https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate/76 . If you don't want to use this feature, let me know.

BTW: @meskobalazs You didn't have maintainer status in this repository, so I've sent you invite. You should be able to approve this pull request after you accept it.

**Comment by Rebootcodesoft** [comment]
Ok, Thank you!

**Review by meskobalazs — APPROVED** [review]
I have reviewed the changes, everything seems to be in order.

**Comment by robbot006** [comment]
Success! Now you can announce new release on [forum](https://discuss.flarum.org/t/languages):

~~~markdown
## Version [`v2.1.0`](https://github.com/flarum-lang/hungarian/releases/tag/v2.1.0)

**General changes**:

* Updated Flarum core translations.


**Added support for new extensions**:

* [`clarkwinkelmann/flarum-ext-discussion-bookmarks`](https://github.com/clarkwinkelmann/flarum-ext-discussion-bookmarks)
* [`clarkwinkelmann/flarum-ext-ipsum-autocomplete`](https://github.com/clarkwinkelmann/flarum-ext-ipsum-autocomplete)
* [`clarkwinkelmann/flarum-ext-see-past-first-post`](https://github.com/clarkwinkelmann/flarum-ext-see-past-first-post)
* [`clarkwinkelmann/flarum-ext-shadow-ban`](https://github.com/clarkwinkelmann/flarum-ext-shadow-ban)
* [`clarkwinkelmann/flarum-ext-who-read`](https://github.com/clarkwinkelmann/flarum-ext-who-read)
* [`datitisev/flarum-discussion-agree-message`](https://github.com/datitisev/flarum-discussion-agree-message)
* [`datlechin/flarum-bbcode-hide-content`](https://github.com/datlechin/flarum-bbcode-hide-content)
* [`datlechin/flarum-copy-links`](https://github.com/datlechin/flarum-copy-links)
* [`datlechin/flarum-discussion-overview`](https://github.com/datlechin/flarum-discussion-overview)
* [`datlechin/flarum-landing-page`](https://github.com/datlechin/flarum-landing-page)
* [`datlechin/flarum-link-preview`](https://github.com/datlechin/flarum-link-preview)
* [`datlechin/flarum-more-discussions`](https://github.com/datlechin/flarum-more-discussions)
* [`datlechin/flarum-offline-indicator`](https://github.com/datlechin/flarum-offline-indicator)
* [`datlechin/flarum-scroll-buttons`](https://github.com/datlechin/flarum-scroll-buttons)
* [`datlechin/flarum-tag-passwords`](https://github.com/datlechin/flarum-tag-passwords)
* [`datlechin/flarum-title-length`](https://github.com/datlechin/flarum-title-length)
* [`davwheat/flarum-ext-ads`](https://github.com/davwheat/flarum-ext-ads)
* [`dem13n/discussion-cards`](https://github.com/Dem13n/discussion-cards)
* [`extiverse/mercury`](https://github.com/extiverse/mercury)
* [`flamarkt/backoffice`](https://github.com/flamarkt/backoffice)
* [`flamarkt/matomo`](https://github.com/flamarkt/matomo)
* [`flamarkt/taxonomies`](https://github.com/flamarkt/taxonomies)
* [`fof/discussion-thumbnail`](https://github.com/FriendsOfFlarum/discussion-thumbnail)
* [`fof/mason`](https://github.com/FriendsOfFlarum/mason)
* [`fof/sentry`](https://github.com/FriendsOfFlarum/sentry)
* [`fof/username-request`](https://github.com/FriendsOfFlarum/username-request)
* [`fof/webhooks`](https://github.com/FriendsOfFlarum/webhooks)
* [`ganuonglachanh/sonic`](https://github.com/ganuonglachanh/flarum-sonic)
* [`glowingblue/password-strength`](https://github.com/glowingblue/flarum-ext-password-strength)
* [`glowingblue/redis-setup`](https://github.com/glowingblue/flarum-ext-redis-setup)
* [`ianm/gravatar`](https://github.com/imorland/gravatar)
* [`ianm/oauth-amazon`](https://github.com/imorland/flarum-ext-oauth-amazon)
* [`jslirola/flarum-ext-login2seeplus`](https://github.com/jslirola/flarum-ext-login2seeplus)
* [`justoverclock/auto-post-count-badge`](https://github.com/justoverclockl/auto-post-count-badge)
* [`justoverclock/best-answer-badge`](https://github.com/justoverclockl/best-answer-badge)
* [`justoverclock/broken-links-checker`](https://github.com/justoverclockl/broken-links-checker)
* [`justoverclock/country-flags`](https://github.com/justoverclockl/country-flags)
* [`justoverclock/custom-header`](https://github.com/justoverclockl/custom-header)
* [`justoverclock/edit-posts`](https://github.com/justoverclockl/edit-posts)
* [`justoverclock/events-countdown`](https://github.com/justoverclockl/events-countdown)
* [`justoverclock/flarum-ext-feedback`](https://github.com/justoverclockl/flarum-ext-feedback)
* [`justoverclock/flachat`](https://github.com/justoverclockl/flachat)
* [`matteocontrini/flarum-imgur-upload`](https://github.com/matteocontrini/flarum-imgur-upload)
* [`migratetoflarum/fake-data`](https://github.com/migratetoflarum/fake-data)
* [`nearata/flarum-ext-embed-video`](https://github.com/Nearata/flarum-ext-embed-video)
* [`nearata/flarum-ext-tags-color-generator`](https://github.com/Nearata/flarum-ext-tags-color-generator)
* [`sycho/flarum-advanced-extension-categories`](https://github.com/SychO9/flarum-advanced-extension-categories)
* [`sycho/flarum-move-posts`](https://github.com/SychO9/flarum-move-posts)
* [`the-turk/flarum-diff`](https://github.com/the-turk/flarum-diff)
* [`the-turk/flarum-stickiest`](https://github.com/the-turk/flarum-stickiest)
* [`therealsujitk/flarum-ext-gifs`](https://github.com/therealsujitk/flarum-ext-gifs)
* [`tituspijean/flarum-ext-auth-ldap`](https://github.com/tituspijean/flarum-ext-auth-ldap)
* [`xelson/flarum-ext-chat`](https://github.com/Xelson/flarum-ext-chat)


**Updated translations for extensions**:

* [`blomstra/payments`](https://extiverse.com/extension/blomstra/payments)
* [`clarkwinkelmann/flarum-ext-scout`](https://github.com/clarkwinkelmann/flarum-ext-scout)
* [`justoverclock/flarum-ext-hashtag`](https://github.com/justoverclockl/flarum-ext-hashtag)


All changes: [v2.0.17...v2.1.0](https://github.com/flarum-lang/hungarian/compare/v2.0.17...v2.1.0).

In order to update run these commands:

```console
composer update flarum-lang/hungarian
php flarum cache:clear
```

~~~

**Pull request merged**
